services:
  # Web service for the Streamlit app
  - type: web
    name: cricket-image-chatbot
    env: python
    region: singapore
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m nltk.downloader punkt wordnet omw-1.4 averaged_perceptron_tagger
    startCommand: gunicorn wsgi:app --timeout 120 --log-level debug
    envVars:
      # Aiven PostgreSQL database credentials
      # These should be updated with your actual Aiven PostgreSQL credentials
      - key: DB_NAME
        value: defaultdb
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        value: YOUR_AIVEN_PASSWORD_HERE
      - key: DB_HOST
        value: pg-3c5659d2-saneeipk-09e5.k.aivencloud.com
      - key: DB_PORT
        value: '20432'
      # Groq API key for LLM service
      - key: GROQ_API_KEY
        sync: false
      # Ensure Python output is not buffered
      - key: PYTHONUNBUFFERED
        value: 'true'
      # Add port for Streamlit
      - key: PORT
        value: '10000'
    healthCheckPath: /
    # Increase the health check timeout
    healthCheckTimeout: 300
