# Aiven PostgreSQL credentials (for deployment on Streamlit Community Cloud)
DB_NAME = "defaultdb"
DB_USER = "avnadmin"
DB_PASSWORD = "AVNS_v9_DecaS2FUYb_sv6dI"
DB_HOST = "pg-fa357dd-jaspreet639703-f821.j.aivencloud.com"
DB_PORT = "24832" 

# LLaMA API settings
LLAMA_API_KEY=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
LLAMA_API_URL=https://api.llama-api.com
