# Aiven PostgreSQL credentials (for deployment on Streamlit Community Cloud)
DB_NAME = "defaultdb"
DB_USER = "avnadmin"
DB_PASSWORD = "AVNS_v9_DecaS2FUYb_sv6dI"
DB_HOST = "pg-fa357dd-jaspreet639703-f821.j.aivencloud.com"
DB_PORT = "24832" 

# LLaMA API settings (deprecated)
LLAMA_API_KEY = "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"
LLAMA_API_URL = "https://api.llama-api.com"

# Groq API settings
GROQ_API_KEY = "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"
GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"
GROQ_MODEL = "llama-3.3-70b-versatile"

# Embedding model
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
